POST https://api.bitume2000.fr/v2/role/category
Authorization: bearer {{token}}
accept: application/json
content-type: application/json

{
  "name": "Combat",
  "color" : "E91E1E"
}



###
GET https://api.bitume2000.fr/v2/role/category
Authorization: bearer {{token}}
Accept: application/json

###

POST https://api.bitume2000.fr/v2/role
Authorization: bearer {{token}}
accept: application/json
content-type: application/json

{
  "name": "Grésivaudan",
  "category": 1

}
