GET http://localhost:42000/v2/members
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODIyODcxNzIsImV4cCI6MTY4MjM3MzU3Mn0.MaUkpKBBhkGOanUTLul7Cfojd-klK6bRdrhjohaFwIg
Accept: application/json

###
