GET https://api.bitume2000.fr/v2/members/avatar
Content-Type: application/x-www-form-urlencoded
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd3aWxob2EiLCJpc0FkbWluIjpmYWxzZSwiaWQiOiIzMTU0MzEzOTI3ODk5MjE3OTMiLCJpYXQiOjE3MDE1MzY4MTMsImV4cCI6MTcwMTU0NDAxM30.Qbz76wKQHXdK4Noq2eDCDRl3Ymas5DYn5o1WwN2jvnM
